### ISSUE TITLE
Missing tables

### ISSUE THREAD

**Issue by brandonp1551** [fu-dream-team/rest-api#7]
Experiences [
   name, company worked with, date, entry, image
]

Award [
  award name, description, date awarded, winner
]

**Comment by CAD97** [comment]
Opportunities

**Comment by yaja95** [comment]
StudentProjects[
- project name
- project description
-likes counter?
- filter options
- new project submissions 
]

**Comment by yaja95** [comment]
FacultyProjects/Scholars[
- project name
- project description
-likes counter?
- filter options
- new project submissions
- Scholar name
- Scholar image
- Scholar description 
]

**Comment by yaja95** [comment]
For all project opportunities, she wants the user to be able to seach projects by certain filters, so we'll need a table for those. The categories are:
- Summer
- Fall
- Spring
- Internship
-On-Campus
- Off-Campus(local)
- Off-Campus(non-local)
- Paid
-Unpaid
- Offers Course Credit
- Study Away
